
#ifndef _SDKCONFIG_H_
#define _SDKCONFIG_H_

#define CONFIG_MBEDTLS_XTEA_C 1
#define CONFIG_MBEDTLS_KEY_EXCHANGE_RSA 1
#define CONFIG_MBEDTLS_AES_C 1
#define CONFIG_MBEDTLS_RSA_BITLEN_MIN 2048
#define CONFIG_MBEDTLS_SSL_PROTO_TLS1 1
#define CONFIG_MBEDTLS_ECDH_C 1
#define CONFIG_MBEDTLS_PEM_WRITE_C 1
#define CONFIG_MBEDTLS_SSL_OUT_CONTENT_LEN 4096
#define CONFIG_STDK_IOT_CORE_USE_MBEDTLS 1
#define CONFIG_SSL_USING_MBEDTLS 1
#define CONFIG_MBEDTLS_ECP_DP_CURVE25519_ENABLED 1
#define CONFIG_MBEDTLS_ECP_C 1
#define CONFIG_MBEDTLS_RC4_DISABLED 1
#define CONFIG_MBEDTLS_X509_CRL_PARSE_C 1
#define CONFIG_LIBSODIUM_USE_MBEDTLS_SHA 1
#define CONFIG_MBEDTLS_RSA_BITLEN_2048 1
#define CONFIG_MBEDTLS_SSL_PROTO_TLS1_1 1
#define CONFIG_MBEDTLS_X509_CSR_PARSE_C 1
#define CONFIG_MBEDTLS_PEM_PARSE_C 1
#define CONFIG_MBEDTLS_SSL_PROTO_TLS1_2 1
#define CONFIG_MBEDTLS_TLS_ENABLED 1
#define CONFIG_MBEDTLS_TLS_CLIENT 1
#define CONFIG_MBEDTLS_ECP_DP_SECP256R1_ENABLED 1
#define CONFIG_MBEDTLS_HAVE_TIME 1
#define CONFIG_MBEDTLS_TLS_CLIENT_ONLY 1
#define CONFIG_MBEDTLS_SSL_IN_CONTENT_LEN 6144
#define CONFIG_STDK_MQTT_USE_SSL
#define CONFIG_STDK_IOT_CORE_EASYSETUP_HTTP_USE_SOCKET_API

#endif
