########################################
# user Config
########################################

CONFIG_STDK_IOT_CORE_SECURITY_BACKEND_SOFTWARE=y
CONFIG_STDK_IOT_CORE_SECURITY_BACKEND_HARDWARE=
CONFIG_STDK_IOT_CORE_EASYSETUP_HTTP_USE_SOCKET_API=y
CONFIG_STDK_IOT_CORE_EASYSETUP_DISCOVERY_SSID=y

