#
#compiler flag config domain
#
#CONFIG_TOOLPREFIX :=
#CONFIG_OPTIMIZATION_LEVEL_RELEASE := 1
#CONFIG_M4_SOFTFP := 1

#
#board config domain
#
CONFIG_BOARD_FLASH_SIZE := 2

#firmware config domain
#

#set CONFIG_ENABLE_ACP to 1 to enable ACP, set to 0 or comment this line to disable
#CONFIG_ENABLE_ACP:=1
CONFIG_BL_IOT_FW_AP:=1
CONFIG_BL_IOT_FW_AMPDU:=0
CONFIG_BL_IOT_FW_AMSDU:=0
CONFIG_BL_IOT_FW_P2P:=0
CONFIG_ENABLE_PSM_RAM:=1
#CONFIG_ENABLE_CAMERA:=1
#CONFIG_ENABLE_BLSYNC:=1
#CONFIG_ENABLE_VFS_SPI:=1
CONFIG_ENABLE_VFS_ROMFS:=1
CONFIG_ADC_ENABLE_TSEN:=1
CONFIG_EASYFLASH_ENABLE:=1

CONFIG_COMPONENT_BUGKILLER_ENABLE:=1

CONFIG_FREERTOS_TICKLESS_MODE:=1

CONFIG_SYS_APP_TASK_STACK_SIZE:=4096
CONFIG_SYS_APP_TASK_PRIORITY:=15
CONFIG_SYS_VFS_ENABLE:=1
CONFIG_SYS_VFS_UART_ENABLE:=1
CONFIG_SYS_AOS_CLI_ENABLE:=1
CONFIG_SYS_AOS_LOOP_ENABLE:=1
CONFIG_SYS_BLOG_ENABLE:=1
CONFIG_SYS_DMA_ENABLE:=1
CONFIG_SYS_USER_VFS_ROMFS_ENABLE:=1

CONFIG_USE_XTAL32K:=0
CONFIG_ENABLE_STACK_OVERFLOW_CHECK:=0

#mbedtls
CONFIG_MBEDTLS_AES_USE_HW:=1
CONFIG_MBEDTLS_BIGNUM_USE_HW:=1
CONFIG_MBEDTLS_ECC_USE_HW:=1
CONFIG_MBEDTLS_ECP_DP_CURVE25519_ENABLED:=1

#wifi diagnosis
CONFIG_TD_DIAGNOSIS_STA:=1

#blog enable components format :=blog_testc cli vfs helper
LOG_ENABLED_COMPONENTS:=blog_testc hosal loopset looprt bloop blestack src switch_example
ifeq ($(CONFIG_BT_MESH_SYNC),1)
LOG_ENABLED_COMPONENTS += blsync_ble
endif
CONFIG_BL602_USE_ROM_DRIVER:=1
CONFIG_BL602_USE_1M_FLASH:=0

CONFIG_BT_STACK_PTS:=0

CONF_ENABLE_COREDUMP:=1

# STDK config

CONFIG_STDK_IOT_CORE:=y
CONFIG_STDK_IOT_CORE_BSP_SUPPORT_BL602:=y
CONFIG_STDK_IOT_CORE_OS_SUPPORT_FREERTOS:=y
CONFIG_STDK_IOT_CORE_USE_MBEDTLS:=y
CONFIG_STDK_IOT_CORE_NET_MBEDTLS:=y
# CONFIG_STDK_IOT_CORE_EASYSETUP_DISCOVERY_SSID=y
# CONFIG_STDK_IOT_CORE_EASYSETUP_HTTP=y
# CONFIG_LWIP_USE_HTTPD_FOR_EASYSETUP=y
CONFIG_STDK_IOT_CORE_EASYSETUP_BLE=y
CONFIG_STDK_IOT_CORE_EASYSETUP_DISCOVERY_ADVERTISER=y
CONFIG_STDK_IOT_CORE_SECURITY_BACKEND_SOFTWARE:=y
# CONFIG_MBEDTLS_ECDH_LEGACY_CONTEXT:=y
CONFIG_STDK_IOT_CORE_CRYPTO_SUPPORT_ED25519:=y
CONFIG_STDK_IOT_CORE_SECURITY_BACKEND_SOFTWARE:=y


CONFIG_STDK_DEBUG_MEMORY_CHECK=y
# Log Level
CONFIG_STDK_IOT_CORE_LOG_LEVEL_ERROR=y
CONFIG_STDK_IOT_CORE_LOG_LEVEL_WARN=y
CONFIG_STDK_IOT_CORE_LOG_LEVEL_INFO=y
CONFIG_STDK_IOT_CORE_LOG_LEVEL_DEBUG=

# BLE
CONFIG_BT:=1
CONFIG_BT_PERIPHERAL:=1
CONFIG_BT_CENTRAL:=1
CONFIG_BT_OBSERVER:=1
CONFIG_BT_CONN:=1
CONFIG_BLE_TP_SERVER:=1
CONFIG_BT_SMP:=1
CONFIG_BT_FIXED_PASSKEY:=1
CONFIG_BT_SETTINGS:=1
CONFIG_BT_MESH := 1
CONFIG_BLE_STACK_DBG_PRINT := 1
CONFIG_BT_STACK_PTS := 0


ifeq ($(CONFIG_STDK_IOT_CORE_LOG_LEVEL_ERROR),y)
CPPFLAGS += -DCONFIG_STDK_IOT_CORE_LOG_LEVEL_ERROR
endif

ifeq ($(CONFIG_STDK_IOT_CORE_LOG_LEVEL_WARN),y)
CPPFLAGS += -DCONFIG_STDK_IOT_CORE_LOG_LEVEL_WARN
endif

ifeq ($(CONFIG_STDK_IOT_CORE_LOG_LEVEL_INFO),y)
CPPFLAGS += -DCONFIG_STDK_IOT_CORE_LOG_LEVEL_INFO
endif

ifeq ($(CONFIG_STDK_IOT_CORE_LOG_LEVEL_DEBUG),y)
CPPFLAGS += -DCONFIG_STDK_IOT_CORE_LOG_LEVEL_DEBUG
endif

ifeq ($(CONFIG_MBEDTLS_ECP_DP_CURVE25519_ENABLED),1)
CPPFLAGS += -DMBEDTLS_ECP_DP_CURVE25519_ENABLED
endif


ifeq ($(CONFIG_STDK_IOT_CORE_CRYPTO_SUPPORT_ED25519),y)
CPPFLAGS += -DCONFIG_STDK_IOT_CORE_CRYPTO_SUPPORT_ED25519
endif

ifeq ($(CONFIG_STDK_IOT_CORE_SECURITY_BACKEND_SOFTWARE),y)
CFLAGS += -DCONFIG_STDK_IOT_CORE_SECURITY_BACKEND_SOFTWARE
endif

CFLAGS += -DBFLB_BLE
ifeq ($(CONFIG_STDK_IOT_CORE_EASYSETUP_BLE),y)
CPPFLAGS += -DCONFIG_STDK_IOT_CORE_EASYSETUP_BLE
endif

ifeq ($(CONFIG_STDK_IOT_CORE_EASYSETUP_DISCOVERY_ADVERTISER),y)
CPPFLAGS += -DCONFIG_STDK_IOT_CORE_EASYSETUP_DISCOVERY_ADVERTISER
endif

