########################################
# user Config
########################################

CONFIG_STDK_IOT_CORE_SECURITY_BACKEND_SOFTWARE=y
CONFIG_STDK_IOT_CORE_SECURITY_BACKEND_HARDWARE=
CONFIG_STDK_IOT_CORE_EASYSETUP_HTTP_USE_SOCKET_API=y
CONFIG_STDK_IOT_CORE_EASYSETUP_DISCOVERY_SSID=y

CONFIG_STDK_IOT_CORE_LOG_LEVEL_WARN=n
CONFIG_STDK_IOT_CORE_LOG_LEVEL_ERROR=y
CONFIG_STDK_IOT_CORE_LOG_LEVEL_INFO=n
CONFIG_STDK_IOT_CORE_LOG_LEVEL_DEBUG=n
